feat: add tabBarSpacing property
satya164/react-native-tab-view pull request #1142
Opened 2021-03-11 10:35 UTC by mlecoq

### Motivation

The goal is to support spacing between tabs ( see #1020 ) - It is roughly doable with some customizations (thanks to `renderTabBarItem` and `renderIndicator` methods) but it requires to modify internal methods (`getTranslateX` for example)  

### Test plan

I have added one example ( `TabBarSpacingExample` )

2021-04-08 09:47 UTC, blueberry6401 commented
@satya164 What do you think about this? It's very nice if we have this props.

2021-06-18 05:07 UTC, dparrelli commented
Would definitely find this feature quite useful 👍

2021-09-01 01:26 UTC, Hirbod commented
Also add my vote on this 👍

2022-01-19 13:59 UTC, Kerumen commented
@mlecoq Do you have some time to rebase the PR? 🙏🏻 

This way @satya164 can have a look and maybe include it in the next release!

2022-01-19 21:04 UTC, mlecoq commented
@Kerumen I'll make it soon (tomorrow)

2022-01-31 13:00 UTC, Kerumen approved these changes

2022-03-24 02:11 UTC, felipejh commented
Would definitely find this feature quite useful +1

2022-08-31 17:59 UTC, okwasniewski commented
Hey @mlecoq, thanks for your PR! Can you rebase this with the main branch? I will review this once you rebase it and test it again current pager-version.

2022-08-31 19:01 UTC, mlecoq commented
> Hey @mlecoq, thanks for your PR! Can you rebase this with the main branch? I will review this once you rebase it and test it again current pager-version.

Done !

2022-08-31 20:17 UTC, okwasniewski requested changes

2022-08-31 20:17 UTC, okwasniewski commented on src/TabBar.tsx
> +  tabBarSpacing: number;
This should be optional, and default to 0.

2022-08-31 20:17 UTC, okwasniewski commented on example/src/AutoWidthTabBarExample.tsx
> +      tabBarSpacing: number;
Remove this from all the examples, after making it optional.

2022-08-31 20:17 UTC, okwasniewski commented on src/TabView.tsx
> +  ) => React.ReactNode;
Go back to the old formatting to minimise the diff.

2022-08-31 20:17 UTC, okwasniewski commented on src/TabBar.tsx
> +    const separatorPercent = (separatorsWidth / tabBarWidth) * 100;
You can move this near the declaration of `separatorsWidth` to have related calculations one after the other

2022-08-31 20:17 UTC, okwasniewski commented on example/src/TabBarSpacingExample.tsx
> +    padding: 0,
Let's stick with the default padding, so remove this line.

2022-09-01 07:34 UTC, okwasniewski reviewed
Also just for naming, please remove the `tabBar` prefix and change the name to `gap` to match the CSS property which does the same thing

2022-09-01 07:34 UTC, okwasniewski commented on src/TabView.tsx
> +  tabBarSpacing = 0,
The prop should directly be passed to the TabBar, doesn't make sense to pass it to TabView when all it would do is pass it to TabBar

2022-09-01 18:18 UTC, okwasniewski approved these changes

2022-09-01 18:19 UTC, merged